- README.md
Any questions should be directed to @nguyenervu
---
:question:
:question:
1. :question:
:question:
> add domain

- .github/workflows/prisma-migrations.yml
---
:question:
:question:
1. :question:
:question:
> chore: run db migration every merge

- .github/workflows/prisma-migrations.yml
---
:question:
:question:
1. :question:
:question:
> chore: fix ci db push

- .github/workflows/prisma-migrations.yml
- package.json
---
:question:
:question:
1. :question:
:question:
> chore: expose prisma migrate with top level script

- README.md
---
:question:
:question:
1. :question:
:question:
> Prisma migration badge

- scripts/postInstall.sh
---
:question:
:question:
1. :question:
:question:
> chore: fix codespace setup

- package.json
---
:question:
:question:
1. :question:
:question:
> chore: add a npm script to launch just a vubnguyen

- turbo.json
---
:question:
:question:
1. :question:
:question:
> Order tasks

- packages/db/package.json
- turbo.json
---
:question:
:question:
1. :question:
:question:
> ci: fix turbo task

- .devcontainer/devcontainer.json
- .env.example
- .vscode/settings.json
- scripts/postInstall.sh
---
:question:
:question:
1. :question:
:question:
> dev: update for codespace to use zsh by default

- .vscode/settings.json
---
:question:
:question:
1. :question:
:question:
> fix: set my fonts for codespaces

- .husky/pre-commit
- .lintstagedrc.mjs
- apps/vubnguyen/package.json
- apps/vubnguyen/src/app/layout.tsx
- apps/vubnguyen/src/app/page.tsx
- apps/vubnguyen/src/app/posts.tsx
- apps/vubnguyen/src/app/providers.tsx
- apps/vubnguyen/tsconfig.json
- package.json
- packages/auth/package.json
- packages/classnames/index.ts
- packages/classnames/package.json
- packages/classnames/tsconfig.json
- packages/db/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
---
:question:
:question:
1. :question:
:question:
> Classnames

- apps/vubnguyen/src/app/layout.tsx
- apps/vubnguyen/src/app/page.tsx
- apps/vubnguyen/src/app/posts.tsx
- apps/vubnguyen/src/components/Header.tsx
---
:question:
:question:
1. :question:
:question:
> feat: navbar

- apps/vubnguyen/src/components/Header.tsx
---
:question:
:question:
1. :question:
:question:
> fix: navbar issues

- apps/vubnguyen/src/app/layout.tsx
---
:question:
:question:
1. :question:
:question:
> add transition to light/dark mode change

- apps/vubnguyen/src/components/Header.tsx
- apps/vubnguyen/src/components/theme-switcher.tsx
---
:question:
:question:
1. :question:
:question:
> chore default is light theme

- apps/vubnguyen/src/components/theme-switcher.tsx
---
:question:
:question:
1. :question:
:question:
> fix: no render theme toggle untill on client

- .github/workflows/release.yml
---
:question:
:question:
1. :question:
:question:
> feat: setup for npm publish

- .github/workflows/release.yml
---
:question:
:question:
1. :question:
:question:
> fix: proper cli for publish

- apps/vubnguyen/package.json
- apps/vubnguyen/src/app/page.tsx
- apps/vubnguyen/src/app/posts.tsx
- apps/vubnguyen/src/components/Header.tsx
- apps/vubnguyen/src/components/auth.tsx
- apps/vubnguyen/src/components/theme-switcher.tsx
- packages/config/eslint/react.js
---
:question:
:question:
1. :question:
:question:
> chore: update react eslint rules

- .github/workflows/release.yml
- lerna.json
---
:question:
:question:
1. :question:
:question:
> chore: fix ga action for release

- .github/workflows/release.yml
- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> fix: versions

- .github/workflows/release.yml
- apps/vubnguyen/package.json
- apps/vubnguyen/src/app/api/trpc/[trpc]/route.ts
- apps/vubnguyen/src/app/layout.tsx
- apps/vubnguyen/src/app/providers.tsx
- apps/vubnguyen/src/components/Header.tsx
- apps/vubnguyen/src/components/posts.tsx
- apps/vubnguyen/src/components/signature.tsx
- apps/vubnguyen/src/env.mjs
- lerna.json
- packages/api/package.json
- packages/api/src/router/auth.ts
- packages/api/src/router/post.ts
- packages/api/src/trpc.ts
- packages/auth/index.ts
- packages/auth/package.json
- packages/classnames/package.json
- packages/config/eslint/base.js
- packages/config/eslint/package.json
- packages/config/eslint/react.js
- pnpm-lock.yaml
- prettier.config.mjs
---
:question:
:question:
1. :question:
:question:
> feat: eslint sort keys

- apps/vubnguyen/src/components/Header.tsx
---
:question:
:question:
1. :question:
:question:
> fix: typing mismatch causing missing guard check

- apps/vubnguyen/src/components/Header.tsx
- apps/vubnguyen/src/components/signature.tsx
---
:question:
:question:
1. :question:
:question:
> fix: remove svg width

- .github/workflows/ci.yml
- README.md
- apps/vubnguyen/package.json
- apps/vubnguyen/src/components/Header.tsx
- lerna.json
- packages/api/package.json
- packages/auth/package.json
- packages/classnames/package.json
- packages/config/eslint/README.md
- packages/config/eslint/package.json
- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> docs: update readme

- packages/config/eslint/base.js
---
:question:
:question:
1. :question:
:question:
> fix: turn off eslint indent rule in favor of prettier

- turbo.json
---
:question:
:question:
1. :question:
:question:
> change dep

- turbo.json
---
:question:
:question:
1. :question:
:question:
> chore: cache outputs on lint:fix

- .devcontainer/devcontainer.json
- .github/renovate.json
- .vscode/launch.json
- .vscode/settings.json
- apps/storybook/.babelrc.json
- apps/storybook/tsconfig.json
- apps/vubnguyen/tsconfig.json
- package.json
- packages/vujita-ui/tsconfig.json
- pnpm-lock.yaml
- prettier.config.mjs
- tsconfig.json
- turbo.json
---
:question:
:question:
1. :question:
:question:
> feat: use prettier sort json

- .devcontainer/devcontainer.json
- turbo.json
---
:question:
:question:
1. :question:
:question:
> chore: add port for storybook

- .env.example
- .gitignore
- apps/storybook/package.json
- pnpm-lock.yaml
- turbo.json
---
:question:
:question:
1. :question:
:question:
> feat: chromatic

- apps/vubnguyen/package.json
- apps/vubnguyen/src/app/api/auth/[...nextauth]/route.ts
- apps/vubnguyen/src/components/Header.tsx
- apps/vubnguyen/src/components/auth.tsx
- packages/api/package.json
- packages/api/src/trpc.ts
- packages/auth/index.ts
- packages/auth/package.json
- pnpm-lock.yaml
> Revert "chore(deps): bump next-auth from 0.0.0-manual.83c4ebd1 to 4.20.1 in /packages/auth"

- apps/vubnguyen/package.json
- apps/vubnguyen/src/app/api/auth/[...nextauth]/route.ts
- apps/vubnguyen/src/components/Header.tsx
- apps/vubnguyen/src/components/auth.tsx
- apps/vubnguyen/src/components/theme-switcher.tsx
- package.json
- packages/auth/index.ts
- packages/auth/package.json
- pnpm-lock.yaml
- turbo.json
---
:question:
:question:
1. :question:
:question:
> chore: update next-auth

- turbo.json
---
:question:
:question:
1. :question:
:question:
> chore: remove disabling of cache

- .github/workflows/deploy-gh-pages.yml
- README.md
---
:question:
:question:
1. :question:
:question:
> feat: deploy storybook -> gh pages

- .github/workflows/deploy-gh-pages.yml
---
:question:
:question:
1. :question:
:question:
> chore: fix ignore gh pages not running build/lint

- .github/workflows/deploy-gh-pages.yml
---
:question:
:question:
1. :question:
:question:
> fix: change gh deploy syntax

- .eslintignore
- .github/workflows/ci.yml
- .github/workflows/playwright.yml
- .husky/pre-push
- .prettierignore
- apps/storybook/package.json
- apps/vubnguyen/.gitignore
- apps/vubnguyen/e2e/example.spec.ts
- apps/vubnguyen/package.json
- apps/vubnguyen/playwright.config.ts
- apps/vubnguyen/tsconfig.json
- package.json
- packages/api/package.json
- packages/auth/package.json
- packages/config/eslint/base.js
- packages/vujita-ui/.eslintignore
- packages/vujita-ui/babel.config.cjs
- packages/vujita-ui/jest.config.ts
- packages/vujita-ui/package.json
- packages/vujita-ui/src/classnames.test.ts
- packages/vujita-ui/tsconfig.json
- pnpm-lock.yaml
- turbo.json
---
:question:
:question:
1. :question:
:question:
> feat: add e2e/jest

- scripts/postInstall.sh
---
:question:
:question:
1. :question:
:question:
> fix: codespaces add install playwright

- package.json
- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> fix: add daemon false for turbo.json

- apps/storybook/package.json
- apps/storybook/vercel.json
---
:question:
:question:
1. :question:
:question:
> fix: ignore storybook branch

- apps/storybook/package.json
- apps/storybook/vercel.json
Reverts vujita/vubnguyen#76
didn't prevent vercel preview link
> Revert "fix: ignore storybook branch"

- apps/vubnguyen/src/components/Header.tsx
- package.json
- packages/vujita-ui/package.json
- packages/vujita-ui/src/avatar.tsx
- packages/vujita-ui/test/classnames.test.ts
- packages/vujita-ui/tsconfig.json
- pnpm-lock.yaml
- turbo.json
---
:question:
:question:
1. :question:
:question:
> chore: cleanup avatar component

- apps/vubnguyen/src/styles/globals.css
---
:question:
:question:
1. :question:
:question:
> chore: import vujita-ui css to get all css variables

- apps/perf-extension/manifest.json
- apps/perf-extension/src/popup.html
- apps/perf-extension/src/popup.tsx
- apps/perf-extension/vite.config.ts
> feat: add a popup page

- .github/workflows/playwright-cron.yml
- apps/vubnguyen/e2e/example.spec.ts
- turbo.json
Run host check on portfolio every hour
> chore: add host env

- apps/vubnguyen/src/components/Header.tsx
---
:question:
:question:
1. :question:
:question:
> chore: improve spacing on header

- apps/vubnguyen/package.json
- apps/vubnguyen/src/app/layout.tsx
- apps/vubnguyen/src/components/Header.tsx
- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> fix: issue with downloading font from next/font package

- .github/workflows/deploy-gh-pages.yml
---
:question:
:question:
1. :question:
:question:
> Fix storybook

- packages/vujita-ui/package.json
- turbo.json
---
:question:
:question:
1. :question:
:question:
> chore: fix storybook build task

- .github/workflows/ci.yml
- .github/workflows/playwright.yml
- turbo.json
---
:question:
:question:
1. :question:
:question:
> chore: add turbo cache for gha

- .github/workflows/db-migrations.yml
---
:question:
:question:
1. :question:
:question:
> chore: add db migrate to use turbo cache

- .github/workflows/ci.yml
- .github/workflows/playwright.yml
---
:question:
:question:
1. :question:
:question:
> chore: fix playwright binary cache

- .github/workflows/ci.yml
- .github/workflows/db-migrations.yml
- .github/workflows/playwright.yml
---
:question:
:question:
1. :question:
:question:
> Cache keys

- apps/vubnguyen/src/app/page.tsx
- packages/vujita-ui/.storybook/main.ts
- packages/vujita-ui/src/avatar.stories.tsx
- packages/vujita-ui/src/index.tsx
- packages/vujita-ui/src/skeleton.tsx
---
:question:
:question:
1. :question:
:question:
> feat: add simple skeleton component

- .vscode/settings.json
---
:question:
:question:
1. :question:
:question:
> chore: fix vscode eslint setting

- .github/workflows/ci.yml
---
:question:
:question:
1. :question:
:question:
> chore: change ci gha

- apps/vubnguyen/playwright.config.ts
---
:question:
:question:
1. :question:
:question:
> chore: fix e2e to run locally despite https errs

- .github/workflows/ci.yml
---
:question:
:question:
1. :question:
:question:
> chore: change cache key

- .github/workflows/ci.yml
- .github/workflows/playwright.yml
---
:question:
:question:
1. :question:
:question:
> Cache key 2

- .github/workflows/ci.yml
- .github/workflows/deploy-gh-pages.yml
---
:question:
:question:
1. :question:
:question:
> fix: try using turbo envs

- .github/workflows/deploy-gh-pages.yml
---
:question:
:question:
1. :question:
:question:
> chore: remove un-used envs

- .github/dependabot.yml
---
:question:
:question:
1. :question:
:question:
> chore: add dependabot yml

- scripts/postInstall.sh
- turbo.json
---
:question:
:question:
1. :question:
:question:
> chore: fixes

- .github/workflows/ci.yml
- .github/workflows/db-migrations.yml
- .github/workflows/deploy-gh-pages.yml
- .github/workflows/playwright.yml
---
:question:
:question:
1. :question:
:question:
> chore: update when cache is pulled in gha

- .devcontainer/devcontainer.json
---
:question:
:question:
1. :question:
:question:
> chore: allow codespaces to read other repos so my dotfiles can work

- .devcontainer/devcontainer.json
- scripts/codespace-postinstall.sh
- scripts/postInstall.sh
---
:question:
:question:
1. :question:
:question:
> Codespaces setup

- .github/workflows/ci.yml
- .github/workflows/playwright.yml
---
:question:
:question:
1. :question:
:question:
> chore: fix so only 1 ci per PR and more triggers

- .github/workflows/ci.yml
- .github/workflows/db-migrations.yml
- .github/workflows/deploy-gh-pages.yml
- .github/workflows/playwright.yml
---
:question:
:question:
1. :question:
:question:
> chore: remove cp file

- .github/workflows/ci.yml
- .github/workflows/db-migrations.yml
- .github/workflows/deploy-gh-pages.yml
- .github/workflows/playwright.yml
---
:question:
:question:
1. :question:
:question:
> fix: add storbyook build

- apps/perf-extension/package.json
- apps/perf-extension/tailwind.config.ts
- apps/vubnguyen/package.json
- apps/vubnguyen/src/app/layout.tsx
- apps/vubnguyen/src/app/providers.tsx
- apps/vubnguyen/src/components/Header.tsx
- apps/vubnguyen/src/components/auth.tsx
- apps/vubnguyen/src/components/posts.tsx
- apps/vubnguyen/src/components/signature.tsx
- apps/vubnguyen/src/utils/api.ts
- package.json
- packages/api/index.ts
- packages/api/package.json
- packages/api/src/trpc.ts
- packages/auth/index.ts
- packages/auth/package.json
- packages/config/eslint/base.js
- packages/config/eslint/package.json
- packages/db/package.json
- packages/vujita-ui/jest.config.ts
- packages/vujita-ui/package.json
- packages/vujita-ui/src/avatar.stories.tsx
- packages/vujita-ui/src/avatar.tsx
- packages/vujita-ui/src/classnames.ts
- packages/vujita-ui/src/skeleton.tsx
- packages/vujita-ui/src/tailwind.preset.ts
- packages/vujita-ui/tailwind.config.ts
- packages/vujita-ui/tsup.config.ts
- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> Typescript upgrade

- .github/workflows/ci.yml
---
:question:
:question:
1. :question:
:question:
> chore: add retry to ci tasks

- .github/workflows/ci.yml
- .github/workflows/deploy-gh-pages.yml
- .github/workflows/playwright.yml
- apps/vubnguyen/package.json
- packages/api/package.json
- packages/auth/package.json
- packages/db/package.json
- packages/vujita-ui/package.json
---
:question:
:question:
1. :question:
:question:
> try using vercel caching again

- packages/db/drizzle.config.ts
- packages/db/package.json
- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> drizzile upgrade

- package.json
> Revert "rename script"

- apps/perf-extension/manifest.json
- apps/perf-extension/package.json
- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> add permissions

- pnpm-workspace.yaml
---
:question:
:question:
1. :question:
:question:
> updae syntax for workspace

- apps/newnew-performancetool/.eslintrc.cjs
- apps/newnew-performancetool/package.json
- apps/newnew-performancetool/src/content.tsx
- apps/newnew-performancetool/src/stores/tti.ts
- apps/newnew-performancetool/tsconfig.json
- package.json
- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> Newnew scaffolding

- apps/newnew-performancetool/src/components/MemoryStats.tsx
- apps/newnew-performancetool/src/content.tsx
- apps/newnew-performancetool/src/stores/memory.ts
We can change this to requestIdleCallback later and do it in an infinite recursive call
---
:question:
:question:
1. :question:
:question:
> add memory tracker every 250ms

- apps/vubnguyen/next.config.mjs
---
:question:
:question:
1. :question:
:question:
> remove un-necessary env check for build

- .github/workflows/ci.yml
- packages/db/package.json
- pnpm-lock.yaml
- turbo.json
---
:question:
:question:
1. :question:
:question:
> chore: add missing dep

- .github/workflows/ci.yml
---
:question:
:question:
1. :question:
:question:
> Chore env file

- apps/vubnguyen/src/env.mjs
---
:question:
:question:
1. :question:
:question:
> remove DATABASE_URL from being required for build

- apps/vubnguyen/xclap.ts
- packages/db/package.json
- packages/db/src/db.ts
- packages/db/src/env.ts
- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> Chore build env

- .github/dependabot.yml
---
:question:
:question:
1. :question:
:question:
> add patterns to storybook dependabot group

- .github/dependabot.yml
- package.json
- pnpm-lock.yaml
- turbo.json
---
:question:
:question:
1. :question:
:question:
> chore: general upkeep fixes

- packages/vujita-ui/files/vercel.json
- packages/vujita-ui/package.json
- packages/vujita-ui/tsconfig.json
- packages/vujita-ui/xclap.ts
- turbo.json
---
:question:
:question:
1. :question:
:question:
> Chore vercel ignore gh pages

- apps/vubnguyen/tsconfig.json
- packages/vujita-ui/.storybook/preview.ts
- packages/vujita-ui/package.json
- packages/vujita-ui/tsconfig.json
- packages/vujita-ui/tsconfig.types.json
- packages/vujita-ui/tsup.config.ts
- packages/vujita-ui/xclap.ts
---
:question:
:question:
1. :question:
:question:
> Chore declarationmaps

- turbo.json
---
:question:
:question:
1. :question:
:question:
> prefer terminal stream over tui

- .vscode/extensions.json
---
:question:
:question:
1. :question:
:question:
> remove prisma suggestion

- .github/dependabot.yml
---
:question:
:question:
1. :question:
:question:
> chore-trpc-group

- packages/vujita-ui/package.json
---
:question:
:question:
1. :question:
:question:
> add side effects key

- .github/workflows/ci.yml
- .github/workflows/db-migrations.yml
- .github/workflows/deploy-gh-pages.yml
- .github/workflows/playwright.yml
- .github/workflows/release.yml
---
:question:
:question:
1. :question:
:question:
> chore: fix pnpm setup gha action

- .github/workflows/playwright.yml
---
:question:
:question:
1. :question:
:question:
> chore: fix playwright output path

- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> chore: pnpm dedupe

- package.json
- packages/db/src/schema.ts
---
:question:
:question:
1. :question:
:question:
> Chore tweaks

- .github/workflows/playwright.yml
- apps/vubnguyen/package.json
- apps/vubnguyen/playwright.config.ts
---
:question:
:question:
1. :question:
:question:
> Chore playwright result

- .vscode/extensions.json
- .vscode/settings.json
- packages/config/eslint/base.js
- packages/vujita-ui/tsup.config.ts
---
:question:
:question:
1. :question:
:question:
> Chore fix tailwind config setup

- package.json
Signed-off-by: Vu Nguyen <shardphoneix@gmail.com>
> add manyfix config to allow workspace protocal

- apps/vubnguyen/package.json
---
:question:
:question:
1. :question:
:question:
> update pathing on app level

- apps/vubnguyen/tsconfig.json
- packages/vujita-ui/.eslintignore
- packages/vujita-ui/.storybook/preview.ts
- packages/vujita-ui/package.json
- packages/vujita-ui/tsconfig.json
- packages/vujita-ui/xclap.cjs
- packages/vujita-ui/xclap.ts
---
:question:
:question:
1. :question:
:question:
> src->dist css

- packages/vujita-ui/files/vercel.json
---
:question:
:question:
1. :question:
:question:
> update cmd to stop gh-page from triggerring preview

- packages/vujita-ui/files/vercel.json
> Revert "update cmd to stop gh-page from triggerring preview"

- .github/workflows/deploy-gh-pages.yml
---
:question:
:question:
1. :question:
:question:
> update storybook deploy script

- .github/workflows/playwright.yml
- apps/vubnguyen/package.json
- apps/vubnguyen/src/components/Header.tsx
- apps/vubnguyen/src/components/theme-switcher.tsx
- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> upgrade gha

- apps/vubnguyen/eslint.config.mjs
---
:question:
:question:
1. :question:
:question:
> fix eslint rule for import no resolve false positive

- package.json
- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> bump lerna

- packages/vujita-ui/tsconfig.json
---
:question:
:question:
1. :question:
:question:
> add skip lib check

- apps/vubnguyen/next.config.mjs
- apps/vubnguyen/package.json
- pnpm-lock.yaml
---
:question:
:question:
1. :question:
:question:
> add bundle analyzer

- apps/vubnguyen/next.config.mjs
- apps/vubnguyen/src/app/layout.tsx
- apps/vubnguyen/src/components/Header.tsx
- apps/vubnguyen/src/components/posts.tsx
- package.json
- turbo.json
---
:question:
:question:
1. :question:
:question:
> cleanup remove auth for now

- tsconfig.json
---
:question:
:question:
1. :question:
:question:
> chore: set moduleResolultion to use bundler
